Phone Component
Ordering-Inc/ordering-components pull request #245
Opened 2021-01-27 21:13 UTC by YisusJe

2021-01-29 03:18 UTC, quirozcarlos commented
fix and improve component

2021-02-04 15:00 UTC, carlosq-ordering requested changes

2021-02-04 22:32 UTC, carlosq-ordering commented
Unit testing is missing

2021-02-05 20:26 UTC, carlosq-ordering approved these changes

2021-02-05 20:26 UTC, merged